//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPICarShow.Models
{
    using System;
    using System.Collections.Generic;
    using Newtonsoft.Json;

    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.CarOrder = new HashSet<CarOrder>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_CarBrand { get; set; }
        public Nullable<int> id_TypeBody { get; set; }
        public Nullable<int> id_Engine { get; set; }
        public Nullable<decimal> price { get; set; }
        
        [JsonIgnore]
        public virtual CarBrand CarBrand { get; set; }

        [JsonIgnore]
        public virtual Engine Engine { get; set; }

        [JsonIgnore]
        public virtual TypeBody TypeBody { get; set; }

        [JsonIgnore]
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarOrder> CarOrder { get; set; }
    }
}
